### ISSUE TITLE
Renamed files

### ISSUE THREAD

**Issue by matiux** [radovskyb/watcher#10]
Hi, how can I know the renamed file name?
Where I rename a file, the event "created" is thrown but I get only the old name of the file. This is the code:

```golang
go func() {
	defer wg.Done()

	for {
		select {
		case event := <-w.Event:

			fmt.Println(event)

			fileType := func() string {
				if event.IsDir() {
					return "Directory"
				} else {
					return "File"
				}
			}

			switch event.Op {
			case watcher.Write:
				s := fmt.Sprintf("Wrote %v: %v", fileType(), event.Name())
				fmt.Println(s)
			case watcher.Create:
				s := fmt.Sprintf("Created %v: %v", fileType(), event.Name())
				fmt.Println(s)
			case watcher.Remove:
				s := fmt.Sprintf("Removed %v: %v", fileType(), event.Name())
				fmt.Println(s)
			case watcher.Rename:
				s := fmt.Sprintf("Renamed %v: %v", fileType(), event.Name())
				fmt.Println(s)
			case watcher.Chmod:
				s := fmt.Sprintf("Chmoded %v: %v", fileType(), event.Name())
				fmt.Println(s)
			}
		case err := <-w.Error:
			log.Fatalln(err)
		}
	}
}()
```

I need to know the name of the file after it was renamed. I tried to comment out the line `w.SetMaxEvents(1)` so I thought that All event would be sent but doesn't work

Thanks

**Comment by radovskyb** [comment]
Hey @matiux,

What operating system are you using? The problem could be because of how `watcher` catches rename events, which I haven't fully tested for cross operating system compatibility yet, so I'm thinking maybe your OS is one I haven't yet tested for.

Either way, I do still need to rewrite a fair bit of the code, so if there's anything else, feel free to let me know.

**Comment by radovskyb** [comment]
By the way, when you wrote this:

> Where I rename a file, the event "created" is thrown but I get only the old name of the file.

Did you mean that the event "renamed" is thrown, but you just want to know what the filename was renamed to, or were you actually saying that you are only receiving a `create` event and not a `rename` event.

If you are actually receiving the `rename` event and just want the feature to be able to see what a `rename` event is now renamed to, then that's a much easier issue to solve.

**Comment by matiux** [comment]
Hi @radovskyb thank for you reply.
I'm using Debian GNU Linux 64 bit. It's one of those operating systems that have not been tested yet?

I'll try to explain better

When I rename a file named `test.txt` in `mod-test.txt` I get this log:
```
FILE "test.txt" RENAME [/home/iux/Desktop/GoSyncTest/test.txt]
Renamed File: test.txt
```

As you can see, I obtain only the old name of the file but I need to get Also the new name. Something like `" test.txt -> mod-test.txt "`

**Comment by matiux** [comment]
Update:
I would like to have the full path of the renamed file:

```
" /home/user/GoSyncTest/test.txt -> /home/user/GoSyncTest/mod-test.txt "
```

or if the file was moved in other folder:

```
" /home/user/GoSyncTest/test.txt -> /home/user/GoSyncTest/new_folder/test.txt "
```

**Comment by radovskyb** [comment]
Ah ok I see. It's not an issue of the testing then since the renaming is working. Originally I thought the renaming process wasn't working when you said you only received a `create` event.

I'll be happy add the feature of displaying what the file was renamed to when I get some spare time, but as for checking where a file was moved to, it would probably be pretty easy to work that out when you are checking for events as a user, so for now I might just leave that up to the user to filter, but I might add that feature later on when I get around to re-writing some core functionality for `watcher` (been meaning on it for a while now, but have been busy).

When I get some spare time, I'll have a look into both feature requests :)

**Comment by matiux** [comment]
Thanks @radovskyb .

Is there some workaround for now? I would like to write a program That sync Everything That Happens in a folder, in a mysql database. So I need to watch also changing to the file or directory

**Comment by radovskyb** [comment]
Hmm, I'm not too sure at the moment what would be the best way to go about it at this stage from the user side of things but here is one suggestion you can try out until I get around to looking into it eventually. 

Basically, I'm not sure how many files you are watching or how large they are, however if you are watching a huge amount of large sized files and you are checking for changes say for example every 100ms, then this is probably not going to be a great idea because of the time it might takes to process file checksums, but one thing you could try in the meantime is to store checksums for all of the files that you are watching, then anytime a file is removed from one directory and another file is created in another directory, which could be a move, you could see if the removed file and the created file share the same checksum, mod time and other file properties, which would most likely mean that the file was moved and is the same file.

The same method could also be used for checking what a file was renamed to.

In the meantime before I personally add this feature, if you want a quick fix just to see the new name of a renamed file, just edit the version of `watcher` that's stored on your system and in the file `watcher.go` on line 373, change `Path: path2` to `Path: path1 + " -> " + path2`, which will then display something like the following for a `rename` event: `DIRECTORY "a" RENAME [tmp/c -> tmp/a]`.

**Comment by matiux** [comment]
Thanks @radovskyb.
The directory that I need to watch contains approximately 500 file. Some of these also weigh 15Gb. But the changes in this folder (add, delete, rename, moving ecc) are done by me manually occasionally, and especially one file at time. So I would not worry of the time to process file checksum.

later I will try to to modify watcher.go as you suggested :)

Thanks!

**Comment by matiux** [comment]
Hi @radovskyb 

for now I have edit watcher.go:

```golang
path:     path2 + " -> " + path1,
```
so I get old and new file. Then I have created a regexp to obtain the two single values (old and new filename):

```golang
r := regexp.MustCompile(`^(FILE|DIRECTORY)\s"([^"]*)"\sRENAME\s\[(([^\s]|\s[^-]|\s-[^>]|\s->[^\s])*)\s->\s([^\]]*)\]$`)

parts := r.FindAllStringSubmatch(event.String(), -1)

fmt.Printf("Old: %v\n", parts[0][3])
fmt.Printf("New: %v\n", parts[0][5])
```

and works.

But I have another problem. When I move a file into a directory, for example `/directory/file.txt -> /directory/subdirectory/file.txt` I get only this:

```
FILE "file.txt" CREATE [/directory/subdirectory/file.txt]
Created File: file.txt
```

I'd like to have also some information about the old position or on remove action. For instance 

```
FILE "file.txt" CREATE [/directory/subdirectory/file.txt]
Created File: file.txt
FILE "file.txt" REMOVE [/directory/file.txt]
Removed File: file.txt
```
Or even better:

```
FILE "file.txt" RENAME [/directory/file.txt -> /directory/subdirectory/file.txt]
Old: /directory/file.txt
New: /directory/subdirectory/file.txt
```

What do you think about that? I think that the second solution could be the right way

**Comment by radovskyb** [comment]
Hey again @matiux,

Just for a quick suggestion, rather than using regex to retrieve the old and the new path from modifying the path, it's much simpler to use something like the following instead:

```go
splitPath := strings.Split(event.Path, " -> ")
old := splitPath[0]
new := splitPath[1]
```

Anyway, when I suggested editing `watcher.go`, that was only to show rename's from within a folder, not from when moving from one folder to another folder.

The suggestion that I gave you in my earlier comment with using checksums and mod times from files deleted in one folder and then created in another folder is how I recommended that you check for a file move, since I don't have the time for me to properly write up a solution especially since I need to rewrite certain parts of `watcher` already anyway.

The other issue with me currently trying to implement a `move` event directly into `watcher` is because it could cause large unnecessary slowdowns when there are lots of events occuring since to find a `move` event, it would have to check every single `remove` and `create` event across directories to do comparisons, not to mention that storing and checking checksums for every potential event would simply be too slow for most cases.

When I eventually rewrite some specific parts of `watcher`, I'll more than likely add in a proper way to retrieve the old and new paths for file rename events coming from inside the same directory, but for now I don't think I'll be adding in a `move` event because of what's needed for it, but this doesn't mean I won't try to work out a good solution eventually :)

**Comment by matiux** [comment]
Unfortunately I did not understand how to use the checksum to handle the rename but maybe for now I found a solution.

I have setted `w.SetMaxEvents(2)` so when the move event occurs, I get two events:

Moving `/directory/file.txt` in `/directory/subdirectory/file.txt`

```
FILE "a.txt" CREATE [/directory/subdirectory/file.txt]                                                                                           
Created File: /directory/subdirectory/file.txt                                                                              
FILE "a.txt" REMOVE [/directory/file.txt]                                                                                                    
Removed File: /directory/file.txt
```

For my purpose this is more than sufficient since that thanks to these two events, I can update the record in database

Thanks for your time :)

**Comment by radovskyb** [comment]
Oh cool 😄 I didn't even think to ask you what exactly you needed to achieve so sorry I didn't realize this earlier. The set max events feature is there for when people want to receive only one event per watching cycle but I see that 2 at a time is perfect for you, so glad you found a solution :)

**Comment by radovskyb** [comment]
Hey @matiux,

Just thought I'd let you know that I'm currently working on implementing `move event` functionality in a new branch on my localhost, so when I get some proper time to work on it, I'll let you know one day hopefully soon when it's ready!

**Comment by matiux** [comment]
Wow thanks @radovskyb 
I look forward !

For now I'm using the "remove and create" sequence but is not fully safe

**Comment by radovskyb** [comment]
Hey @matiux, just merged the changes with the master branch so let me know what you think :)

I have also added event filtering (there's an example), so you can choose to only get notified for rename and move events if you like.

Just FYI, a move event only shows up if the file is moved from one watched folder to another watched folder, but won't show if you move the file into a folder that isn't being watched.

**Comment by matiux** [comment]
Thanks @radovskyb I will try asap!

**Comment by radovskyb** [comment]
Just btw, the API is changed slightly, so for recursive watching, use AddRecursive.

**Comment by matiux** [comment]
Uhm... have you a simple example to use new code?

**Comment by radovskyb** [comment]
Sure! Check out the examples folder. I updated the examples to use the new functions (https://github.com/radovskyb/watcher/tree/master/example).

Here's an example for filtering events that returns at most 1 rename or move event per cycle: https://github.com/radovskyb/watcher/blob/master/example/filter_events/main.go.

**Comment by radovskyb** [comment]
Hey @matiux, 

Unless there's anything you're having trouble with, I'll close this issue :)

If there is anything else or you're having any problems, feel free to let me know!

**Comment by matiux** [comment]
Thanks @radovskyb I'm trying the Move feature just now!
I will let you know!

**Comment by matiux** [comment]
I tried the new features about "move" and "rename" events. They seem they work well! :)

I'd like to show you my project to have your opinion about it :)

**Comment by radovskyb** [comment]
Awesome, good to hear! I'll close the issue now but let me know if there's anything else :D
