### ISSUE TITLE
Is this library stable currently??

### ISSUE THREAD

**Issue by 756445638** [radovskyb/watcher#17]

**Comment by radovskyb** [comment]
Hey @756445638,

At this stage, I would have to do more extensive testing across platforms to be sure.

I definitely know that it's possible that there could be some cross compatibility issues with move events on Windows since `os.SameFile` wasn't consistent across platforms and the `SameFile` function I wrote may need some improving for certain unlikely edge cases, however I would still personally use `Watcher` for projects depending on the use case.

If you are working with Unix based operating systems, I would say it's mostly stable since I've had no problems.

Definitely let me know if there is anything that you find that needs improving or seems unstable.

Polling for filesystem events is certainly different that regular filesystem even notifications, which I won't go into why right now, but there is also `fsnotify` (https://github.com/fsnotify/fsnotify) which depending on your use case, you may like to check out.

**Comment by 756445638** [comment]
I used you library in my program,when I write some file at watched directory but I have not receive a event,I don`t know what is wrong!!
I have used this package "https://github.com/fsnotify/fsnotify",but is does not support watch recursively.

**Comment by radovskyb** [comment]
Can you share the code that you're using so I can have a look for you? :)

**Comment by 756445638** [comment]
func StartFsNotify() {
	f := func() error {

		watch := watcher.New()
		fmt.Println("###########", g.Conf.GcConfigConfig.StorageDir)
		defer watch.Close()
		err := watch.Add(g.Conf.GcConfigConfig.StorageDir)
		if err != nil {
			return err
		}
		err = watch.Start(time.Millisecond * 50)
		if err != nil {
			return err
		}
		for {
			select {
			case err = <-watch.Error:
				return err
			case e := <-watch.Event:
				fmt.Println("###########", e.Path)

				t := strings.Split(e.Path, "storage")
				name := t[len(t)-1]
				name = strings.Replace(name, `\`, `/`, -1)
				FsNotifyObj.notify(name)
			}
		}
	}

	for {
		err := f()
		if err != nil {
			log.Warnf("watch failed,err:%v\n", err)
		}
		time.Sleep(time.Millisecond * 50)
	}
}

**Comment by 756445638** [comment]
Dell@yuyang-computer MINGW32 /d/dev/gopath/src/hmi-server/opserver/static/ht-editor/instance-backendless/storage
$ go env
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=D:\dev\gopath
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\Dell\AppData\Local\Temp\go-build622196699=/tmp/go-build -gno-record-gcc-switches
set CXX=g++
set CGO_ENABLED=1
set PKG_CONFIG=pkg-config
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2

Dell@yuyang-computer MINGW32 /d/dev/gopath/src/hmi-server/opserver/static/ht-editor/instance-backendless/storage
$ go version
go version go1.8 windows/amd64

Dell@yuyang-computer MINGW32 /d/dev/gopath/src/hmi-server/opserver/static/ht-editor/instance-backendless/storage

**Comment by 756445638** [comment]
I run example program directly,I change  directory to test_folder and execute "echo 11 >> 22",I have not see something came out of stdout!!

**Comment by radovskyb** [comment]
Here is a minimalistic example:

```
package main

import (
	"fmt"
	"log"
	"time"

	"github.com/radovskyb/watcher"
)

func main() {
	watch := watcher.New()

	err := watch.Add(".")
	if err != nil {
		log.Fatalln(err)
	}

	go func() {
		for {
			select {
			case err := <-watch.Error:
				fmt.Println(err)
			case e := <-watch.Event:
				fmt.Println("###########", e.Path)
			case <-watch.Closed:
				return
			}
		}
	}()

	err = watch.Start(time.Millisecond * 50)
	if err != nil {
		log.Fatalln(err)
	}
}
```

**Comment by radovskyb** [comment]
Just keep in mind that if you are trying to watch recursively you will need to use `AddRecursive("test_folder")` and not `Add("test_folder")`

**Comment by radovskyb** [comment]
Hey @756445638,

I'm going to close this issue now, however if continue to have any issues with this, feel free to comment here and I will re-open the issue or if you have any new problems, feel free to create a new issue.

**Comment by 756445638** [comment]
ok,thanks!
