### ISSUE TITLE
Support for globs

### ISSUE THREAD

**Issue by kbirk** [radovskyb/watcher#19]
Would it be possible for the watcher API to support Globs as arguments to the `Add` and `Ignore` methods? This would make watching specific directories for only certain file types much easier:

```golang
w.Add("./**/*.go")
```

Or is there a way to achieve this with the current interface?

**Comment by TheWinds** [comment]
Add a filter function may be a better way.
w.Add(path,filter)
```
func filter(fileName string) bool
```

**Comment by skinnyjames** [comment]
Is there a good way to go about this with the CLI?

**Comment by radovskyb** [comment]
Hey guys!

For now I would think, the easiest way to do this would be to use the filepath.Glob method that the standard library provides for adding and ignoring files... :)

(If it seems reasonable to shortcut this and allow globs directly in the add and ignore methods I can consider that too)

For example:

```
package main

import (
	"fmt"
	"log"
	"path/filepath"

	"github.com/radovskyb/watcher"
)

func main() {
	w := watcher.New()

	paths, err := filepath.Glob("**/*")
	if err != nil {
		log.Fatalln(err)
	}

	for _, path := range paths {
		err := w.Add(path)
		if err != nil {
			log.Fatalln(err)
		}
	}

	for path := range w.WatchedFiles() {
		fmt.Println(path)
	}

	// ...
}
```

However, one thing to note is that it would decrease performance if the plan was to have the globs for ignoring files update in between polling to see if any other files added match the glob (if the polling duration is a short one), since it would have to re-glob to see if there were any other files that need to be ignored. If the plan is simply to just ignore what's already there though, then filepath.Glob should be sufficient like within the above example.

I hope that makes sense!

**Comment by radovskyb** [comment]
Did using filepath.Glob work out for you @kbirk? :)

@skinnyjames Was the CLI question something that you might find useful? Feel free to submit any pull requests if you want by the way, but otherwise I might be able to chuck it in the CLI sometime soonish.

**Comment by tj** [comment]
noticed it picks up changes to .git as well by default

**Comment by kbirk** [comment]
Yes it did work, thank you :). Eventually I needed the globs to be run between polling to check for file additions so I ended up writing my own solution down the line. You can close this issue if you like.

**Comment by tmaiaroto** [comment]
Please do add this to the CLI. I'd love to not use fswatch.
