### ISSUE TITLE
Observing high CPU Usage when watching on large directories. Expected? 

### ISSUE THREAD

**Issue by harshavardhana** [radovskyb/watcher#24]
I have a few questions regarding the library itself

- Since there is a constant file walking don't you think crawling in this manner 
  would spin the disks up all the time?
- There are no asynchronous awake events, is there a possibility events might get lost?
- Some small tests seem to work fine, but i am worried about large directories and deep d
  directory structures?

**Comment by radovskyb** [comment]
Hey @harshavardhana,

High CPU would be expected when polling large directories (with a short polling duration at least). Unfortunately with filesystem polling and small poll durations, this is a side effect for trying to achieve real time events notifications.

There are alternatives such as fsnotify that may be better for this type of issue since it actually uses filesystem event notifications and not filesystem polling. Watcher was created to not have to use filesystem events, but there are pros and cons depending on what you're trying to achieve.

As for events getting lost, this also comes back to the previous point where if you were to poll for a long duration and before a poll cycle 3 writes happen to a file, you would only receive a single event once the poll cycle runs that the file has been modified. If you need 100 percent of events I would go with a non-polling option for sure.

On point 3, I still have lots more tests that need writing, but as of right now, I've manually tested/used watcher in deeply nested structures and haven't had any problems so far, but if anything comes up, let me know!

Regards, Benji
