### ISSUE TITLE
How to add notification via email?

### ISSUE THREAD

**Issue by cxnam** [radovskyb/watcher#4]
Hi,
I want notificaiton to email. How it work via email?

Thanks.

**Comment by radovskyb** [comment]
Hey @cxnam, are you referring to sending an email when an event is received?

If so, are you using the watcher cmd or the watcher package with your Go code?

**Comment by cxnam** [comment]
Hi @radovskyb,

Yes, i want sending a email when an event received, and email when sending include lastest event + time event.

I using watcher cmd with python script send mail but not include "lastest event + time event."

sorry my bad english. tks

**Comment by radovskyb** [comment]
Hey again @cxnam,

I have not yet added functionality to `watcher` to allow piping stdout to the command's stdout, however I am more than happy to add this as a feature.

However, in the meantime you can achieve what you would like, by simply starting your python script with something like the following and running `watcher` without the `cmd` flag:

```python
import sys

while 1:
    print sys.stdin.readline()
```

This will print the event any time one is received. You can also add the time to the event in this script if you would like since this is not currently a feature of `watcher` yet either.

For the above to work properly, make sure you re-install watcher as I have just added a new flag that will prevent watcher from listing all of the files since otherwise your script will list them all too. If you would like all of the files that are being listed, enable it with the `-list` flag.

**Comment by cxnam** [comment]
Thanks @radovskyb

**Comment by radovskyb** [comment]
@cxnam, I have added a simple `pipe` flag to the `watcher` cmd that sends event info to the command's stdin when changes are detected.

If you check out the new README you can see an example how to use it with a simple `python` script :)
