### ISSUE TITLE
show full path file changed and fix error python code readme

### ISSUE THREAD

**Issue by cocodrino** [radovskyb/watcher#5]
Hi..I'm curious: It's possible show the full path for the file change, right now with the samples I only get the file name

2) seems than there is a small error in the python code, must be

```python

import sys

for line in sys.stdin:
    print (line + " - python")

```

3) How would be the performance in a very deep folder structure?...can I watch for my whole filesystem?

thanks!!

**Comment by radovskyb** [comment]
Hey @cocodrino,

As of right now, you can retrieve only the `os.FileInfo` from the file that the event is based on. However, if you think it's a good idea, I'm more than happy to add retrieving the full path as a new feature.

With the python code from the `watcher` cmd example, when I wrote it I only tested it with python 2.7 and it worked fine, but after your comment I see that it isn't compatible with python 3 so I'll change it so it works with both versions so thanks for that input :)

Lastly, I wouldn't currently recommend watching very large folder structures (definitely not an entire filesystem), at least not until I add better concurrency (currently watches folder by folder), but it really depends on your interval period, since if you only need to check for changes once every 10-20 minutes, then there should be no issue, however if you want to watch your whole filesystem in real time, I would recommend looking at `fsnotify` instead.

Personally, I have no trouble watching one of my folders that I use regularly which contains approximately 3.5k files, but I think if I added a few more thousand files to the mix it, it would start to lag and could get harsh on my processor.

Kind regards, Benjamin.

**Comment by cocodrino** [comment]
thanks @radovskyb, yes, for me check the changes every 20 minutes would be fine, I'll be alert about your project and improvements, so far works really great for my requeriments..

**Comment by radovskyb** [comment]
@cocodrino, I actually just realized that on my computer, I can personally watch just over 100k files with only about a 1s delay before I see an event, although at about 250k files, the delay is closer to about 5-10s, so I guess if your filesystem isn't super large, you might not have too much of an issue if you don't need to poll so often :)
