### ISSUE TITLE
Watch all files

### ISSUE THREAD

**Issue by ericmdantas** [radovskyb/watcher#7]
Is there any way to watch all files in given folder? Say I'm in the root of my app and I want to watch everything, is there such thing as passing a single dot (`.`)? Some libs in node-land do that, not sure what's the convention for go?

**Comment by radovskyb** [comment]
Hey @ericmdantas,

I'm not totally sure what you mean since currently by default `watcher` is already recursive.
For example if the root folder for your project is called `myproject`, by simply adding that folder with `w.Add("myproject")`, all of the files and folders will be watched recursively from that directory inwards.

Do you mean something else?

**Comment by ericmdantas** [comment]
Sorry for not being clear.

I mean a way to do it explicitly, because when you're using a 3rd party lib that uses `watcher`, for example, it'll not know what's the name of the current/root folder right away, so I just think it'd make sense to provide a way to make that explicit. 

Something like: did the user provide a folder to be watched? No? Then `.` it is. If he did, then `name_provided` it is.

Let me know what you think.

**Comment by ericmdantas** [comment]
Here's an example with node's `chokidar`:

```js
var chokidar = require('chokidar');

// One-liner for current directory, ignores .dotfiles
chokidar.watch('.', {ignored: /[\/\\]\./}).on('all', (event, path) => {
  console.log(event, path);
});
```

**Comment by radovskyb** [comment]
I think I get what you mean..

Are you saying that instead of how currently when calling `Start` without having added any files or folders, instead of how it currently returns an error letting you know that no files have been added, it should just watch whatever directory the code is being called from?

If so, I could probably add that in pretty easily by using `os.Getwd()` if nothing was added to the watch list.

**Comment by ericmdantas** [comment]
> Or are you more specifically suggesting that I allow that if w.Add() is passed a ., then I add the current directory?

This one :smile: 

Do you think it makes sense for your project? I'd understand if it's not the case.

**Comment by radovskyb** [comment]
Hey @ericmdantas, had to head out yesterday so sorry for late reply.

Anyway I get what you're saying, but do you think it's really needed to use something like `.` when in Go we can simply use `os.Getwd()`?

**Comment by ericmdantas** [comment]
I mean, it'd be easier to a newcomer in go, but I know what you mean. Let's keep it simple, then :smile:

**Comment by ericmdantas** [comment]
Closing.

**Comment by radovskyb** [comment]
Hey @ericmdantas,

I decided just to add this feature since it I knew it would just take a minute to implement anyway, so you can now use `w.Add(".")` and `w.Add("..")` :)

**Comment by ericmdantas** [comment]
Awesome, thanks!
