### ISSUE TITLE
watcher misses events for the same file if they were generated within one pollInterval

### ISSUE THREAD

**Issue by Ch00k** [radovskyb/watcher#9]
This code will reproduce the problem:
```go
package main

import (
	"log"
	"time"

	"github.com/radovskyb/watcher"
)

const watchDir = "/Users/ay/tmp/watch"

func main() {
	w := watcher.New()

	go func() {
		for {
			select {
			case event := <-w.Event:
				log.Println(event, event.Name(), event.ModTime())
			case err := <-w.Error:
				panic(err)
			}
		}
	}()

	if err := w.Add(watchDir); err != nil {
		panic(err)
	}

	if err := w.Start(time.Millisecond * 100); err != nil {
		panic(err)
	}
}
```
Run it, then in another terminal `cd` to the watched directory (`/Users/ay/tmp/watch` in this case) and execute `touch 1; rm 1`, which will miss both events, or `touch 1; echo "test" > 1`, which will miss the CREATE event.

**Comment by radovskyb** [comment]
Hey @Ch00k,

Currently being a polling watcher, the way that `watcher` is written, noticing a create and remove for the same file inside of a single cycle is hard to detect.

I am however currently working on rewriting parts of `watcher`, but it will a fair while before the code is ready, yet technically when it's ready, multiple events per file in between cycles should be noticed, at least with the exception of creating and then straight away deleting a file, since this is much harder to detect with a polling watcher.

If you do need this functionality for now, I would definitely recommend checking out fsnotify, since it should pick up both events with no issue since it is based around filesystem event notifications.

If you do also have any suggestions that could help with this issue, feel free to let me know here :)

**Comment by Ch00k** [comment]
@radovskyb I kinda expected that this would be very hard to impossible to fix/implement because of the nature of polling approach.

**Comment by radovskyb** [comment]
@Ch00k, yeah, pretty much.

Since polling consists of checking for a change every specified duration, if for example a file is added and deleted during a cycle, only what is there when the cycle is over can really be checked, so I doubt it's an easy thing to find a solution for.

**Comment by Ch00k** [comment]
@radovskyb I think this one can be closed, unless you want it open to track the work you've mentioned earlier.
